# Generated by Django 5.1.1 on 2024-10-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('adminid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('contact', models.URLField()),
                ('img', models.ImageField(upload_to='static/img/% Y/% m/% d/')),
            ],
        ),
    ]
