# Generated by Django 5.1.1 on 2024-10-23 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=200)),
                ('permission', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='app_admin/static/img/cat/')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.admin_acc')),
            ],
        ),
    ]
