# Generated by Django 5.1.1 on 2024-10-16 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='img',
            field=models.ImageField(upload_to='app_admin/static/img/'),
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('roomid', models.AutoField(primary_key=True, serialize=False)),
                ('roomname', models.CharField(max_length=200)),
                ('timelenght', models.IntegerField(max_length=2)),
                ('approval', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('room_img', models.ImageField(upload_to='app_admin/static/img/rooms/')),
                ('adminid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.admin')),
            ],
        ),
    ]
