# Generated by Django 5.1.1 on 2024-10-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_alter_admin_img_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False)),
                ('catname', models.CharField(max_length=200)),
                ('permission', models.BooleanField(default=False)),
            ],
        ),
    ]
