# Generated by Django 5.1.1 on 2024-10-23 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=200)),
                ('timelenght', models.IntegerField()),
                ('approval', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='app_admin/static/img/rooms/')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.admin_acc')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.category')),
            ],
        ),
    ]
