# Generated by Django 5.1.1 on 2024-11-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='address',
            field=models.CharField(default='Invalid', max_length=255),
        ),
    ]
