# Generated by Django 5.1.1 on 2024-11-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0004_category_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='time',
            field=models.CharField(default='Invalid', max_length=100),
        ),
    ]
