# Generated by Django 5.1.1 on 2024-11-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0005_category_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='note',
            field=models.CharField(default='Invalid', max_length=255),
        ),
    ]
