# Generated by Django 5.1.1 on 2024-11-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0006_category_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='time',
            field=models.CharField(default='08:00-20:00', max_length=100),
        ),
    ]
