# Generated by Django 5.1.1 on 2024-10-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('facid', models.AutoField(primary_key=True, serialize=False)),
                ('facname', models.CharField(max_length=200)),
            ],
        ),
    ]
