# Generated by Django 5.1.1 on 2024-10-23 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('majorname', models.CharField(max_length=200)),
                ('facid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.faculty')),
            ],
        ),
    ]
