# Generated by Django 5.1.1 on 2024-10-16 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_category'),
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('bookid', models.AutoField(primary_key=True, serialize=False)),
                ('datebook', models.DateField()),
                ('timebook', models.TimeField()),
                ('roomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.room')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.user')),
            ],
        ),
    ]
