# Generated by Django 5.1.1 on 2024-10-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_alter_user_userid_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('facid', models.AutoField(primary_key=True, serialize=False)),
                ('facname', models.CharField(max_length=200)),
            ],
        ),
    ]
