# Generated by Django 5.1.1 on 2024-10-23 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=13)),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='app_user/static/img/')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.faculty')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.major')),
            ],
        ),
    ]
