# Generated by Django 5.1.1 on 2024-10-22 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='major',
            fields=[
                ('majorid', models.AutoField(primary_key=True, serialize=False)),
                ('majorname', models.CharField(max_length=200)),
                ('facid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.faculty')),
            ],
        ),
    ]
