# Generated by Django 5.1.1 on 2024-10-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_room'),
        ('app_user', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datebook', models.DateField()),
                ('timebook', models.TimeField()),
                ('reason', models.CharField(max_length=200, null=True)),
                ('room', models.ManyToManyField(to='app_admin.room')),
                ('user', models.ManyToManyField(to='app_user.user')),
            ],
        ),
    ]
