# Generated by Django 5.1.1 on 2024-11-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='datebook',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='timebook',
            field=models.CharField(max_length=200),
        ),
    ]
