# Generated by Django 5.1.1 on 2024-11-07 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0007_alter_category_time'),
        ('app_user', '0009_alter_booking_room_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='app_admin.room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='app_user.user'),
        ),
    ]
