# Generated by Django 5.1.1 on 2024-11-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0007_alter_category_time'),
        ('app_user', '0010_alter_booking_room_alter_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ManyToManyField(to='app_admin.room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ManyToManyField(to='app_user.user'),
        ),
    ]
